### PR TITLE
display default TopN with --flow-top-n-circuit

### PR DESCRIPTION
**Pull request by nanji-fmad**

### CODE REVIEW

**Comment by fmadio** [comment]
Looks good I think, really need to get the coding style guide

This is how want for loop definition to be like:
https://github.com/fmadio/pcap2json/pull/20/commits/f4b6c8e153269592f5a9b7a382e9c2a9534b4ccc#diff-e78303a36c0c122dcbaaba1a51f27d92L1918

**Comment by nanji-fmad** [comment]
> Looks good I think, really need to get the coding style guide
> 
> This is how want for loop definition to be like:
> [f4b6c8e#diff-e78303a36c0c122dcbaaba1a51f27d92L1918](https://github.com/fmadio/pcap2json/commit/f4b6c8e153269592f5a9b7a382e9c2a9534b4ccc#diff-e78303a36c0c122dcbaaba1a51f27d92L1918)

Hi, I want to access variable "i" outside the for loop as well. If you want me to strictly follow the guide then I can take extra variable and and keep increment with for loop "i". But it would be extra overhead !

**Comment by fmadio** [comment]
Would say the readability is better using ? 

SortList[g_FlowTopNMac]

**Comment by fmadio** [comment]
merged, thanks

**Pull request merged**
